# Generated by Django 4.2.6 on 2023-10-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
