# Generated by Django 4.2.6 on 2023-10-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_file_data_rename_img_employees_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_data',
            name='files',
            field=models.FileField(upload_to='media'),
        ),
    ]
