# Generated by Django 4.2.6 on 2023-10-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_alter_file_data_files'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File_Data',
        ),
        migrations.AlterField(
            model_name='employees',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
