# Generated by Django 4.2.6 on 2023-10-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_alter_file_data_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='file_data',
            name='files',
            field=models.FileField(upload_to='media'),
        ),
    ]
